#!/bin/bash -x
for dev 
do
   (
     cd ${dev} && (
       sha512sum -c  ${HOME}/Public/202604/Ventoy.SHA512
       echo "rc1="$?
       sha512sum -c  ${HOME}/Public/202604/Secondary.SHA512 
     ) 
   ) | tee ${HOME}/Logs/$(basename ${dev}).check.log 2>&1 & 
done 
wait
for dev
do 
  (
    echo "-- $(basename ${dev}) --"
    cat ${HOME}/Logs/$(basename ${dev}).check.log
  )
done

