#!/bin/bash -x
for dev
do
   (
     cd ${HOME}/Public/202604/Ventoy && rsync -rav --inplace . ${dev}/
     cd ${HOME}/Public/202604/Secondary && rsync -rav --inplace . ${dev}/
     cd ${dev} && (
       sha512sum -c  ${HOME}/Public/202604/Ventoy.SHA512
       sha512sum -c  ${HOME}/Public/202604/Secondary.SHA512
     )
   ) 2>&1 | tee ${HOME}/Logs/$(basename ${dev}).log & 
done
wait
for dev
do 
  (
    echo "-- $(basename ${dev}) --"
    cat ${HOME}/Logs/$(basename ${dev}).log
  )
done

