#!/bin/bash
mkdir -p flat
typeset -i index=0
for directory
do find "$directory" -type f -name "*.jpg" ! -name "TIM*" -print
done | while read fullname
do
  ln "$fullname" flat/$(printf '%08d' $index).jpg
  index=$index+1
done
